sudo: false

language: node_js

node_js:
  - 11

cache:
  directories:
    - $HOME/.npm

matrix:
  fast_finish: true
  include:
    - env: TEST_TYPE=lint
    - env: REACT=16 TEST_TYPE=test:dist
    - env: REACT=16 TEST_TYPE=test:lib
    - env: REACT=16 TEST_TYPE=test:es
    - env: REACT=16 TEST_TYPE=test:dom
    - env: REACT=16 TEST_TYPE=test:node
    - env: REACT=15 TEST_TYPE=test:dist
    - env: REACT=15 TEST_TYPE=test:lib
    - env: REACT=15 TEST_TYPE=test:es
    - env: REACT=15 TEST_TYPE=test:dom
    - env: REACT=15 TEST_TYPE=test:node

before_script:
  - scripts/install-react.sh

script:
  - scripts/travis-script.sh
