# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: ant design

trigger:
  - master

resources:
  repositories:
    - repository: self
      fetchDepth: 1

jobs:
  - job: test
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        TEST_TYPE:
          TEST_TYPE: lint
        REACT16-test:dist:
          REACT: 16
          TEST_TYPE: test:dist
        REACT16-test:lib:
          REACT: 16
          TEST_TYPE: test:lib
        REACT16-test:es:
          REACT: 16
          TEST_TYPE: test:es
        REACT16-test:dom:
          REACT: 16
          TEST_TYPE: test:dom
        REACT16-test:node:
          REACT: 16
          TEST_TYPE: test:node
        REACT15-test:dist:
          REACT: 15
          TEST_TYPE: test:dist
        REACT15-test:lib:
          REACT: 15
          TEST_TYPE: test:lib
        REACT15-test:es:
          REACT: 15
          TEST_TYPE: test:es
        REACT15-test:dom:
          REACT: 15
          TEST_TYPE: test:dom
        REACT15-test:node:
          REACT: 15
          TEST_TYPE: test:node
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: echo $(REACT) $(TEST_TYPE)
        displayName: echo env
      - script: npm install
        displayName: install
      - script: scripts/install-react.sh
        displayName: install-react
      - script: scripts/travis-script.sh
        displayName: test
