version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.ui-test
    volumes:
      - './components:/app/components'
      - './tests:/app/tests'
      - './jest-stare:/app/jest-stare'
      - './dist:/app/dist'
      - '.jest.image.js:/app/.jest.image.js'
      - './imageSnapshots:/app/imageSnapshots'
      - './imageDiffSnapshots:/app/imageDiffSnapshots'
    entrypoint: "jest --config .jest.image.js --no-cache -i"
