blank_issues_enabled: true
contact_links:
  - name: ğŸ†• Create new issue
    url: https://new-issue.ant.design
    about: The issue which is not created via https://new-issue.ant.design will be closed immediately.
  - name: ğŸ†• åˆ›å»ºä¸€ä¸ªæ–° Issue
    url: https://new-issue.ant.design
    about: âš ï¸ æ³¨æ„è¯·ä¸è¦ä½¿ç”¨ä¸Šé¢çš„ Report a vulnerability æŠ¥å‘Šé—®é¢˜ï¼Œè¿™æ˜¯ç”¨æ¥æŠ¥å‘Šå®‰å…¨æ¼æ´çš„ã€‚ä¸æ˜¯ç”¨ https://new-issue.ant.design åˆ›å»ºçš„ issue ä¼šè¢«æœºå™¨äººè‡ªåŠ¨å…³é—­ã€‚
