blank_issues_enabled: true
contact_links:
  - name: ğŸ†• Create new issue
    url: http://new-issue.ant.design
    about: The issue which is not created via http://new-issue.ant.design will be closed immediately.
  - name: ğŸ†• åˆ›å»ºä¸€ä¸ªæ–° Issue
    url: http://new-issue.ant.design
    about: ä¸æ˜¯ç”¨ http://new-issue.ant.design åˆ›å»ºçš„ issue ä¼šè¢«æœºå™¨äººè‡ªåŠ¨å…³é—­ã€‚å¦å¤–ã€å¦‚ä½•ä½¿ç”¨...ã€ç±»é—®é¢˜å»ºè®®ä½¿ç”¨è®¨è®ºåŒº https://github.com/ant-design/ant-design/discussions
