blank_issues_enabled: false
contact_links:
  - name: ğŸ†• Create new issue
    url: https://new-issue.ant.design
    about: The issue which is not created via https://new-issue.ant.design will be closed immediately.
  - name: ğŸ†• åˆ›å»ºä¸€ä¸ªæ–° Issue
    url: https://new-issue.ant.design
    about: ä¸æ˜¯ç”¨ https://new-issue.ant.design åˆ›å»ºçš„ issue ä¼šè¢«æœºå™¨äººè‡ªåŠ¨å…³é—­ã€‚
  - name: ğŸ” Report a Security Vulnerability
    url: https://github.com/ant-design/ant-design/security/advisories/new
    about: Please report security vulnerabilities here. è¯·åœ¨æ­¤æŠ¥å‘Šå®‰å…¨æ¼æ´ã€‚
