name: ğŸ§ Auto Closer

on:
  issues:
    types: [labeled]

jobs:
  close-by-label:
    runs-on: ubuntu-latest
    if: github.event.label.name == '3.x'
    steps:
      - name: Comment on issue
        uses: peter-evans/close-issue@v1
        with:
          comment: "Hi @${{ github.event.issue.user.login }},<br />Current version (3.x) is off the maintenance period. We may not accept pull request or fix bug with it anymore. This topic will be auto closed.<br /><br />ä½ å¥½ @${{ github.event.issue.user.login }},<br />å½“å‰ç‰ˆæœ¬ï¼ˆ3.xï¼‰å·²ç»è¿‡äº†ç»´æŠ¤æœŸã€‚æˆ‘ä»¬ä¸ä¼šå†æ¥å—å¯¹å…¶çš„ç›¸å…³ PR ä¸ issueã€‚å½“å‰ topic ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚"
      
