name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  issue-open-check:
    permissions:
      contents: read  # for visiky/dingtalk-release-notify to get latest release
      issues: write  # for actions-cool/issues-helper to update issues
      pull-requests: write  # for actions-cool/issues-helper to update PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          require: 'write'
          check-bot: true

      - name: check invalid
        if: (contains(github.event.issue.body, 'ant-design-issue-helper') == false) && (steps.checkUser.outputs.require-result == 'false')
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'Invalid'
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](http://new-issue.ant.design) to create an issue, thank you!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä¸ºäº†èƒ½å¤Ÿè¿›è¡Œé«˜æ•ˆæ²Ÿé€šï¼Œæˆ‘ä»¬å¯¹ issue æœ‰ä¸€å®šçš„æ ¼å¼è¦æ±‚ï¼Œä½ çš„ issue å› ä¸ºä¸ç¬¦åˆè¦æ±‚è€Œè¢«è‡ªåŠ¨å…³é—­ã€‚ä½ å¯ä»¥é€šè¿‡ [issue åŠ©æ‰‹](http://new-issue.ant.design) æ¥åˆ›å»º issue ä»¥æ–¹ä¾¿æˆ‘ä»¬å®šä½é”™è¯¯ã€‚è°¢è°¢é…åˆï¼

      - name: check website
        uses: actions-cool/issues-helper@v3
        id: checkid
        with:
          actions: 'check-issue'
          issue-number: ${{ github.event.issue.number }}
          # æ ¼å¼å¦‚ï¼š'x1,x2' or  'x1,x2/y1,y2' æœ€å¤šæ”¯æŒ 2 ä¸ªæ•°ç»„
          title-includes: 'å®˜ç½‘,ç½‘ç«™,å›½å†…,é•œåƒ,mobile ant design,mobile.ant.design,ant design,ant design pro,pro.ant.design/æŒ‚äº†,æŒ‚æ‰äº†,æ— æ³•è®¿é—®,ä¸èƒ½è®¿é—®,è®¿é—®ä¸äº†,å‡ºé—®é¢˜,æ‰“ä¸å¼€,ç™»ä¸ä¸Š,can not open,cannot open,can not be reached'

      - name: deal website
        if: steps.checkid.outputs.check-result == 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Ant Design ç³»åˆ—å®˜ç½‘ç”±äºæŸäº›ä¼—æ‰€å‘¨çŸ¥çš„åŸå› æ— æ³•è®¿é—®ï¼Œå»ºè®®ç¿»å¢™æˆ–è®¿é—®å›½å†…é•œåƒç«™ç‚¹ã€‚

            ## å®˜ç½‘
            * Ant Design: https://ant.design
            * Ant Design Pro: https://pro.ant.design
            * Ant Design Pro Preview : https://preview.pro.ant.design
            * Ant Design Mobile: https://mobile.ant.design
            * Ant Motion: https://motion.ant.design

            ## å›½å†…é•œåƒ
            * å®˜æ–¹é•œåƒ: https://ant-design.antgroup.com/
            * Gitee é•œåƒ: http://ant-design.gitee.io
            * Ant Design 3.x: http://ant-design-3x.gitee.io
            * Ant Design 2.x: http://ant-design-2x.gitee.io
            * Ant Design 1.x: http://ant-design-1x.gitee.io
            * Ant Design Pro: http://ant-design-pro.gitee.io
            * Ant Design Mobile: http://antd-mobile.gitee.io
            * Ant Motion: http://ant-motion.gitee.io
            * Ant Design Pro Preview : https://prosite.z23.web.core.windows.net

      - name: check ie
        if: contains(github.event.issue.body, 'ant-design-issue-helper') == true && contains(github.event.issue.title, 'IE9') == true || contains(github.event.issue.title, 'IE 9') == true || contains(github.event.issue.title, 'IE10') == true || contains(github.event.issue.title, 'IE 10') == true || contains(github.event.issue.title, 'IE11') == true || contains(github.event.issue.title, 'IE 11') == true || contains(github.event.issue.title, 'Internet Explorer') == true || contains(github.event.issue.body, 'IE9') == true || contains(github.event.issue.body, 'IE 9') == true || contains(github.event.issue.body, 'IE10') == true || contains(github.event.issue.body, 'IE 10') == true || contains(github.event.issue.body, 'IE11') == true || contains(github.event.issue.body, 'IE 11') == true || contains(github.event.issue.body, 'Internet Explorer') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'IE | Firefox | Safari,Internet Explorer'

      - name: check ie11-
        if: contains(github.event.issue.body, 'ant-design-issue-helper') == true && contains(github.event.issue.title, 'IE9') == true || contains(github.event.issue.title, 'IE 9') == true || contains(github.event.issue.title, 'IE10') == true || contains(github.event.issue.title, 'IE 10') == true || contains(github.event.issue.body, 'IE9') == true || contains(github.event.issue.body, 'IE 9') == true || contains(github.event.issue.body, 'IE10') == true || contains(github.event.issue.body, 'IE 10') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment, close-issue'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, v4 only support IE11 and above.

      - name: send to dingtalk
        uses: visiky/dingtalk-release-notify@main
        with:
          DING_TALK_TOKEN: ${{ secrets.DINGDING_BOT_TOKEN }}
          notify_title: 'ğŸ”¥ @${{ github.event.issue.user.login }} åˆ›å»ºäº† issueï¼š${{ github.event.issue.title }}'
          notify_body: '### ğŸ”¥ @${{ github.event.issue.user.login }} åˆ›å»ºäº† issueï¼š[${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) <hr /> ![](https://gw.alipayobjects.com/zos/antfincdn/5Cl2G7JjF/jieping2022-03-20%252520xiawu11.06.04.png)'
          notify_footer: '> ğŸ’¬ æ¬¢è¿å‰å¾€ GitHub è¿›è¡Œè®¨è®ºï¼Œç¤¾åŒºå¯èƒ½éœ€è¦ä½ çš„å¸®åŠ©ã€‚'
          at_all: false # whether to ding everybody
