name: Issue Replay

on:
  issues:
    types: [labeled]

jobs:
  replay-help:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v1
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_BOT_NAME }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, master for bugfix and other changes), fill the [Pull Request Template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬å®Œå…¨åŒæ„ä½ çš„æè®®/åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“ [åˆ›å»ºä¸€ä¸ª Pull Request](https://help.github.com/en/articles/creating-a-pull-request) æ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è¯·å°† Pull Request å‘åˆ°æ­£ç¡®çš„åˆ†æ”¯ï¼ˆæ–°ç‰¹æ€§å‘åˆ° feature åˆ†æ”¯ï¼Œå…¶ä»–å‘åˆ° master åˆ†æ”¯ï¼‰ï¼ŒåŠ¡å¿…å¡«å†™ Pull Request å†…çš„[é¢„è®¾æ¨¡æ¿](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)ï¼Œæä¾›æ”¹åŠ¨æ‰€éœ€ç›¸åº”çš„ changelogã€TypeScript å®šä¹‰ã€æµ‹è¯•ç”¨ä¾‹ã€æ–‡æ¡£ç­‰ï¼Œå¹¶ç¡®ä¿ CI é€šè¿‡ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œ Reviewï¼Œæå‰æ„Ÿè°¢å’ŒæœŸå¾…æ‚¨çš„è´¡çŒ®ã€‚

            ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

      - name: ğŸ¤” Need Reproduce
        if: github.event.label.name == 'ğŸ¤” Need Reproduce'
        uses: actions-cool/issues-helper@v1
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_BOT_NAME }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by \`Need Reproduce\` will be closed if no activities in 7 days.

            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚ä½ å¯ä»¥é€šè¿‡ç‚¹å‡» [æ­¤å¤„](https://u.ant.design/codesandbox-repro) åˆ›å»ºä¸€ä¸ª codesandbox æˆ–è€…æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„ GitHub ä»“åº“ã€‚7 å¤©å†…æœªè·Ÿè¿›çš„ issue å°†ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚

            ![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)
      
      - name: Usage
        if: github.event.label.name == 'Usage'
        uses: actions-cool/issues-helper@v1
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_BOT_NAME }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, we use GitHub issues to trace bugs or discuss plans of Ant Design. So, please [don't ask usage questions](https://github.com/ant-design/ant-design/issues/2320) here. You can try to open a new discussion in [antd discussions](https://github.com/ant-design/ant-design/discussions), select `Q&A` to ask questions, also can ask questions on [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) or [Segment Fault](https://segmentfault.com/t/antd), then apply tag `antd` and `react` to your question.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼ŒAnt Design Issue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚è¯·[å‹¿è¯¢é—®å¦‚ä½•ä½¿ç”¨çš„é—®é¢˜](https://github.com/ant-design/ant-design/issues/2320)ï¼Œä½ å¯ä»¥è¯•ç€åœ¨ [antd discussions](https://github.com/ant-design/ant-design/discussions) æ–°å¼€ä¸€ä¸ª discussionï¼Œé€‰æ‹© `Q&A` ç±»åˆ«è¿›è¡Œæé—®ï¼Œä¹Ÿå¯ä»¥åœ¨ [Stack Overflow](http://stackoverflow.com/questions/tagged/antd) æˆ–è€… [Segment Fault](https://segmentfault.com/t/antd) ä¸­æé—®ï¼ˆè®°å¾—æ·»åŠ  `antd` å’Œ `react` æ ‡ç­¾å“¦~ï¼‰ã€‚
