name: Issue Check Inactive

on:
  schedule:
    - cron: "0 */15 * * *"

jobs:
  check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v1
        with:
          actions: 'check-inactive'
          token: ${{ secrets.ANT_BOT_TOKEN }}
          inactive-label: 'Inactive'
          inactive-day: 30
