name: Issue Remove Inactive

on:
  issues:
    types: [edited, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  remove-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: remove inactive
        if: github.event.issue.state == 'open'
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'remove-labels'
          token: ${{ secrets.ANT_BOT_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Inactive,needs-more-info'
