name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need reproduce
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'close-issues'
          token: ${{ secrets.ANT_BOT_TOKEN }}
          labels: 'ğŸ¤” Need Reproduce'
          inactive-day: 3
      
      - name: needs more info
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'close-issues'
          token: ${{ secrets.ANT_BOT_TOKEN }}
          labels: 'needs-more-info'
          inactive-day: 3
          body: |
            Since the issue was labeled with `needs-more-info`, no response was received for 7 days. The issue is now closed. If you have any questions, you can comment and reply.

            ç”±äºè¯¥ issue æ ‡è®° `needs-more-info`ï¼Œå´ 3 å¤©æœªæ”¶åˆ°å›åº”ã€‚ç°å…³é—­ issueã€‚è‹¥æœ‰ä»»ä½•é—®é¢˜ï¼Œå¯è¯„è®ºå›å¤ã€‚
