name: Memer Workflow

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Memer Action
        id: memer

        uses: Bhupesh-V/memer-action@master
        with:
          filter: "new"

      - name: Check Outputs
        run: |
          echo "${{ steps.memer.outputs.meme }}"
          echo "${{ steps.memer.outputs.title }}"
          echo "${{ steps.memer.outputs.source }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1.3.0
        id: couc
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ğŸ‰ğŸ‰ Thanks for opening this PR ğŸ¤—
            Please wait while the maintainer(s) review it

            Meanwhile have a look at this ğŸ˜ :

            > **${{ steps.memer.outputs.title }}**
            ![meme](${{ steps.memer.outputs.meme }})
            <sub>â„¹ï¸ <a href="${{ steps.memer.outputs.source }}">Source</a> [ Powered By ğŸ”¥ <a href="https://github.com/Bhupesh-V/memer-action">Memer Action</a> ]</sub>
