name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - run: corepack enable
      - uses: utooland/setup-utoo@v1

      - name: Install dependencies
        run: ut

      - name: Build
        run: ut build

      # ========== Prepare examples ==========
      - name: Clear examples
        run: rm -rf examples

      - name: Clone examples
        uses: actions/checkout@v6
        with:
          repository: ant-design/ant-design-examples
          path: examples

      - name: Modify examples
        run: utx tsx scripts/prepare-examples.ts

      - run: utx pkg-pr-new publish --template './examples/examples/*'
