# å½“ PR è¢«åˆå¹¶æ—¶ï¼Œç•™è¨€æ¬¢è¿ŽåŠ å…¥å…±å»ºç¾¤
name: PullRequest Contributor Welcome

on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'components/**'

permissions:
  contents: read

jobs:
  comment:
    permissions:
      issues: write  # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write  # for actions-cool/maintain-one-comment to modify or create PR comments
    if: github.event.pull_request.merged == true && github.repository == 'ant-design/ant-design'
    runs-on: ubuntu-latest
    steps:
      - name: get commit count
        id: get_commit_count
        run: |
          PR_AUTHOR=$(echo "${{ github.event.pull_request.user.login }}")
          RESULT_DATA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits?author=${PR_AUTHOR}&per_page=5")
          DATA_LENGTH=$(echo $RESULT_DATA | jq 'if type == "array" then length else 0 end')
          echo "COUNT=$DATA_LENGTH" >> $GITHUB_OUTPUT
      - name: Comment on PR
        if: steps.get_commit_count.outputs.COUNT < 3
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ðŸŽ‰ Thank you for your contribution! If you have not yet joined our DingTalk community group, please feel free to join us (when joining, please provide the link to this PR).

            ðŸŽ‰ æ„Ÿè°¢æ‚¨çš„è´¡çŒ®ï¼å¦‚æžœæ‚¨è¿˜æ²¡æœ‰åŠ å…¥é’‰é’‰ç¤¾åŒºç¾¤ï¼Œè¯·æ‰«æä¸‹æ–¹äºŒç»´ç åŠ å…¥æˆ‘ä»¬ï¼ˆåŠ ç¾¤æ—¶è¯·æä¾›æ­¤ PR é“¾æŽ¥ï¼‰ã€‚

            <img src="https://github.com/user-attachments/assets/cfee105e-8731-481f-a336-92b79a84d35a" height="200" />

            <!-- WELCOME_CONTRIBUTION -->
          body-include: <!-- WELCOME_CONTRIBUTION -->
