# Used to merge master/feature branches with each other
name: PR Check CI

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-pr-ci@v1.1.0
        with:
          filter-label: 'BranchAutoMerge'
          filter-creator-authority: 'write'
          filter-head-ref: 'master, feature, master-merge-feature, feature-merge-master'
          filter-support-fork: false
          success-review: true
          success-merge: true
          merge-method: 'merge'
          merge-title: 'chore: auto merge branchs (#${number})'
