# When `preview-build` start. Leave a message on the PR
#
# ğŸš¨ğŸš¨ğŸš¨ Important ğŸš¨ğŸš¨ğŸš¨
# Never do any `checkout` or `npm install` action!
# `pull_request_target` will enable PR to access the secrets!

name: Preview Start

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  preview-start:
    permissions:
      issues: write  # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write  # for actions-cool/maintain-one-comment to modify or create PR comments
    name: start preview info
    runs-on: ubuntu-latest
    steps:
      - name: update status comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            [<img width="500" alt="Prepare preview" src="https://user-images.githubusercontent.com/5378891/72351368-2c979e00-371b-11ea-9652-eb4e825d745e.gif">](https://preview-${{ github.event.number }}-ant-design.surge.sh)
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
