# Each PR will build preview site that help to check code is work as expect.

name: Preview Deploy

on:
  workflow_run:
    workflows: ["Preview Build"]
    types:
      - completed

jobs:
  deploy-site:
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: download site artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: site-${{ github.event.workflow_run.pull_requests[0].number }}

      - name: upload surge service
        id: deploy
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ github.event.workflow_run.pull_requests[0].number }}-ant-design.surge.sh
          npx surge --project ./ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: update status comment
        uses: actions-cool/maintain-one-comment@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            [<img width="306" src="https://user-images.githubusercontent.com/5378891/72400743-23dbb200-3785-11ea-9d13-1a2d92743846.png">](https://preview-${{ github.event.workflow_run.pull_requests[0].number }}-ant-design.surge.sh)
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'

      - name: The job has failed
        if: steps.deploy.outcome != 'success'
        uses: actions-cool/maintain-one-comment@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <img width="534" src="https://user-images.githubusercontent.com/5378891/75333447-1e63a280-58c1-11ea-975d-235367fd1522.png">
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
