name: ðŸ†‡ Release to X

on:
  create

permissions: {}

jobs:
  tweet:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 5
    if: ${{ github.event.ref_type == 'tag' && !contains(github.event.ref, 'alpha') }}
    steps:
      - name: Tweet
        uses: nearform-actions/github-action-notify-twitter@78c89f569aba92b378bcf69efbabfbc43cc6e564 # pin@master
        with:
          message: |
            ðŸ¤– Ant Design just released antd@${{ github.event.ref }} âœ¨ðŸŽŠâœ¨ Check out the full release note: https://github.com/ant-design/ant-design/releases/tag/${{ github.event.ref }}
          twitter-app-key: ${{ secrets.TWITTER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_API_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
