# Current release process:
# 1. `npm run pub` will call antd-tools `run pub`
# 2. antd-tools `run pub` will generate a new tag
# 3. antd-tools `run pub` will trigger `npm publish` at the same time
# 4. Then the new tag will trigger this current action
# 5. The action will generate a new release, and publish DingDing notification at the same time

name: DingTalk Release Notification

on:
  create

permissions:
  contents: read

jobs:
  release-helper:
    permissions:
      contents: write  # for actions-cool/release-helper to create releases
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Send to Ant Design DingGroup
        uses: actions-cool/release-helper@v2
        with:
          trigger: 'tag'
          changelogs: 'CHANGELOG.en-US.md, CHANGELOG.zh-CN.md'
          branch: 'master, 4.x-stable'
          tag: '5*, 4*'
          latest: '5*'
          dingding-token: ${{ secrets.DINGDING_BOT_TOKEN }} ${{ secrets.DINGDING_BOT_COLLABORATOR_TOKEN }} ${{ secrets.DINGDING_BOT_MAINTAINER_TOKEN }}
          dingding-msg: 'CHANGELOG.zh-CN.md'
          msg-title: '# Ant Design {{v}} å‘å¸ƒæ—¥å¿—'
          msg-poster: 'https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*zx7LTI_ECSAAAAAAAAAAAABkARQnAQ'
          msg-footer: 'ğŸ’¬ å‰å¾€ [**Ant Design Releases**]({{url}}) æŸ¥çœ‹æ›´æ–°æ—¥å¿—'
          prettier: true
          prerelease-filter: '-, a, b, A, B'

      - name: Send to Bigfish DingGroup
        uses: actions-cool/release-helper@v2
        with:
          trigger: 'tag'
          changelogs: 'CHANGELOG.en-US.md, CHANGELOG.zh-CN.md'
          branch: 'master, 4.x-stable'
          tag: '5*, 4*'
          latest: '5*'
          dingding-token: ${{ secrets.DINGDING_BOT_BIGFISH_TOKEN }} ${{ secrets.DINGDING_BOT_BIGFISH_2_TOKEN }} ${{ secrets.DINGDING_BOT_YUNFENGDIE_TOKEN }}
          dingding-msg: 'CHANGELOG.zh-CN.md'
          dingding-delay-minute: 10
          release: false
          conch-tag: 'conch-v5, conch'
          antd-conch-msg: 'ğŸŸ å½“å‰ Bigfish å†…åµŒ antd ç‰ˆæœ¬ï¼š'
          msg-title: '# Ant Design {{v}} å‘å¸ƒæ—¥å¿—'
          msg-poster: 'https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*zx7LTI_ECSAAAAAAAAAAAABkARQnAQ'
          msg-footer: 'ğŸ’¬ å‰å¾€ [**Ant Design Releases**]({{url}}) æŸ¥çœ‹æ›´æ–°æ—¥å¿—'
          prettier: true
          prerelease-filter: '-, a, b, A, B'

