# When pushing a tag. this workflow will trigger site deployment and fixed version address comments

name: Deploy website
on:
  push:
    tags:
      - '6.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    if: (startsWith(github.ref, 'refs/tags/') && (contains(github.ref_name, '-') == false)) || github.event_name == 'workflow_dispatch'

    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-defining-outputs-for-a-job
    outputs:
      formatted_version: ${{ steps.shared-formatted_version.outputs.VERSION }}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - uses: utooland/setup-utoo@v1

      - run: ut

      - name: build site
        run: ut predeploy
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: build dist and bundle analyzer report
        run: ut dist
        env:
          ANALYZER: 1
          NODE_OPTIONS: --max_old_space_size=4096

      - name: move report.html to _site
        run: |
          if [ -f report.html ]; then
            mv report.html _site && echo "report.html moved to _site"
          fi

      - name: upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: real-site
          path: _site/
          retention-days: 1 # Not need to keep for too long

      - name: Format version
        if: ${{ always() }}
        id: shared-formatted_version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/\./-/g')" >> $GITHUB_OUTPUT

  deploy-to-pages:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs: build-site
    steps:
      - uses: utooland/setup-utoo@v1

      - name: download site artifact
        uses: actions/download-artifact@v8
        with:
          name: real-site
          path: _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          exclude_assets: ./_site/report.html
          force_orphan: true

      # Since force_orphan will not trigger Sync to Gitee, we need to force run it here
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:ant-design/ant-design.git'
          destination-repo: 'git@gitee.com:ant-design/ant-design.git'

      - name: Deploy to Surge (with TAG)
        if: ${{ needs.build-site.outputs.formatted_version != 'master' }}
        run: |
          export DEPLOY_DOMAIN=ant-design-${{ needs.build-site.outputs.formatted_version }}.surge.sh
          utx surge --project ./_site --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Create Commit Comment
        if: ${{ needs.build-site.outputs.formatted_version != 'master' }}
        uses: peter-evans/commit-comment@v4
        with:
          body: |
            - Documentation site for this release: https://ant-design-${{ needs.build-site.outputs.formatted_version }}.surge.sh
            - Webpack bundle analyzer report page: https://ant-design-${{ needs.build-site.outputs.formatted_version }}.surge.sh/report.html

  # https://github.com/ant-design/ant-design/pull/49213/files#r1625446496
  upload-to-release:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    # 仅在 tag 的时候工作，因为我们要将内容发布到以 tag 为版本号的 release 里
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-site
    steps:
      - name: download site artifact
        uses: actions/download-artifact@v8
        with:
          name: real-site
          path: _site

      - name: Tarball site
        run: |
          cd ./_site
          tar -czf ../website.tar.gz --transform 's|^|antd-${{ needs.build-site.outputs.formatted_version }}-website/|' .
          cd ..

      - name: Upload to Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          fail_on_unmatched_files: true
          files: website.tar.gz
