name: Trigger Argos manually

on: workflow_dispatch

permissions:
  contents: read

jobs:
  trigger_argos_manually:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install node_modules
        run: yarn
      - name: Build dist file
        run: npm run dist:esbuild
      - name: Run image screenshot tests
        run: npm run test-image
      - name: Upload screenshots to Argos CI
        run: npm run argos