name: Verify Files modify

on:
  pull_request_target:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verify-version
        uses: actions-cool/verify-files-modify@v1.2.2
        with:
          forbid-paths: '.github/, scripts/'
          forbid-files: 'CHANGELOG.zh-CN.md, CHANGELOG.en-US.md, LICENSE'
          skip-verify-authority: 'write'
          assignees: 'afc163, zombieJ, xrkffgg'
          comment: |
            Hi @${{ github.event.pull_request.user.login }}. Thanks for your contribution. The path `.github/` or `scripts/` and `CHANGELOG` `package.json` is only maintained by team members. This current PR will be closed and team members will help on this.
          close: true
  
      - name: verify-less
        uses: actions-cool/verify-files-modify@v1.2.2
        with:
          forbid-files: 'components/style/themes/default.less'
          skip-verify-authority: 'admin'
          comment: |
            ğŸš¨ Hi @${{ github.event.pull_request.user.login }}. Thanks for your contribution, as the `default.less` file is currently being upgraded, changes will not be accepted for the time being.

            ğŸš¨ ä½ å¥½ï¼Œ@${{ github.event.pull_request.user.login }}ã€‚æ„Ÿè°¢ä½ çš„è´¡çŒ®ï¼Œç”±äº `default.less` æ–‡ä»¶è¿‘æœŸå¤„äºå‡çº§çŠ¶æ€ï¼Œæš‚ä¸æ¥å—æ›´æ”¹ã€‚
          close: true
